name: Deploy microservice

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}  # Use the GitHub commit hash for versioning
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Check Docker Compose version to confirm installation

  # Add this step to set executable permissions for the build script
    - name: Make build-image.sh executable
      run: chmod +x ./scripts/build-image.sh
      
    - name: Build and Push Docker image
      run: ./scripts/build-image.sh

    - name: Set up kubectl
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AK_CLUSTER_NAME }}
        kubectl version --client

    - name: Deploy to AKS
      run: ./scripts/deploy.sh
